name: eval_plus
description: "Flutter mobile application for teacher evaluation at UTS. Modern interface enabling students to assess teaching quality and provide academic feedback."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.2
  ms_undraw: ^4.1.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/uts_icon.png"
  adaptive_icon_background: "#D7F0E2"
  adaptive_icon_foreground: "assets/icon/uts_icon.png"

flutter_native_splash:
  color: "#D7F0E2"
  image: assets/icon/uts_icon.png
  android_12:
    image: assets/icon/uts_icon.png
    color: "#D7F0E2"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/illustrations/
    - assets/animations/
