name: eval_plus
description: "Flutter mobile application for teacher evaluation at UTS. Modern interface enabling students to assess teaching quality and provide academic feedback."
publish_to: 'none'
version: 0.5.4-rc+4

environment:
  sdk: ^3.9.2
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.2
  ms_undraw: ^4.1.1
  flutter_svg: ^2.2.1
  webview_flutter: ^4.13.0
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  provider: ^6.1.5+1
  flutter_secure_storage_linux: ^1.2.3
  flutter_secure_storage_windows: ^3.1.2
  path_provider: ^2.1.5
  path_provider_linux: ^2.2.1
  path_provider_windows: ^2.3.0
  shared_preferences: ^2.5.4
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/uts_icon5.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/uts_icon5.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/uts_icon5.png
  android_12:
    image: assets/icon/uts_icon5.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/illustrations/
    - assets/animations/
